### ISSUE TITLE
Tobias "follow url" fields

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#23]
if a tiddler contains a "follow" field with value YES, then also index the wiki pointed by this url.

See https://groups.google.com/d/msg/Tiddlywiki/tJjhzDDvk4k/wraxzGvCSkEJ

**Comment by tobibeer** [comment]
in addition, `follow:no` is explicitly expected not to be followed... in the sense of a blacklist (or as a manual information for you, atm ;-)

**Comment by erwanm** [comment]
sure, but technically once it's implemented the only wiki in my manual list is tb5, and the system doesn't need the two possibilities:  either the default is not to follow anything except if follow==yes, or the default is to follow if there is a follow field and an url except if follow==no. 

I'm more inclined to choose the former because it is more intuitive (default=do nothing), but if it's more convenient for you I can do the other way of course. In any case it saves you the trouble of marking one of the two categories.

**Comment by tobibeer** [comment]
Consider the case where a url in a tiddler previously set to `follow:yes` is now set to `follow:no`.

**Comment by erwanm** [comment]
Oh, of course, now I see the misunderstanding: you assumed that my implementation was smart ;)

It's actually not smart at all (at least currently): the whole wiki is rebuilt every time, i.e. all the tiddlers are extracted, including the ones which were already there. So the system doesn't keep any memory of the previous version, which means that it will read the "follow" field every time anyway, and proceed according to the latest version.

In the future I might improve that, but:
* It will have to take into account modifications to existing tiddlers anyway, so if the field was changed the system will read the new value
* apparently the workload does not depend too much on the number of tiddlers, because downloading and converting the whole wikis to/from node.js is always needed anyway. So as long as it works doing it in the dumb way... why bother? (did I mention that I was a bit lazy? ;) )

**Comment by tobibeer** [comment]
I know your kind of lazy ^^

**Comment by erwanm** [comment]
@tobibeer 
the "follow url" behaviour is implemented and should work from now on. let me know if you see something not working as it should.

**Comment by tobibeer** [comment]
Hi @erwanm, do you have that documented somewhere for reference in terms of how to use it?

**Comment by erwanm** [comment]
I'm working on documentation right now, it will be here: https://rawgit.com/erwanm/tw-aggregator/master/tw-community-search.html#AuthorDocumentation

**Comment by erwanm** [comment]
@tobibeer 

this feature is documented more precisely at https://rawgit.com/erwanm/tw-aggregator/master/tw-community-search.html#FollowUrlFeature
don't hesitate to propose any improvement of course!

**Comment by tobibeer** [comment]
@erwanm: Great stuff, well done!

**Comment by erwanm** [comment]
@tobibeer thank you! you certainly deserve a big thanks yourself for providing half of the indexed content ;)
