### ISSUE TITLE
Search Box Only Tiddler

### ISSUE THREAD

**Issue by RichShumaker** [erwanm/tw-aggregator#26]
It would be cool to embed inside a Tiddler just the search box itself.
Could code be easily created to make something like that?

I am not great at that kind of thing but I will have a go at it some time in the next few days.
I am thinking something like Search and Advanced Search in TW5.
So it would say 'Community Search' and then have a box to put data in.
That way it could be added to sidebars in TiddlyWiki's and things like that.

Rich Shumaker

**Comment by erwanm** [comment]
Actually I was going to say that it's not possible but I'm not sure... anyway I'm not competent to do this kind of web development, unfortunately!
I think I've seen some experiments with iframe on the TW list, I guess this could be a way to do it. I doubt about the possibility of a real integration in the "host wiki", but as I said I'm not really the one to ask ;)

(also this seems related to Mat's questions here: https://groups.google.com/d/msg/Tiddlywiki/eZqoogwCrZ0/imK4qf34mY0J, I don't know if this is useful)

**Comment by erwanm** [comment]
I forgot to mention that the search box tiddler can be accessed at
https://rawgit.com/erwanm/tw-aggregator/master/tw-community-search.html#CommunitySearch:CommunitySearch

**Comment by RichShumaker** [comment]
I think that you have the Tiddler I was looking for in your link above.  There is no ability to search remote TW at this time so putting a search box in my TW to search yours would not work.
That would be an interesting experiment but may bog down the TW you are using as it has to load the remote one in an iframe or some other mechanism.
