### ISSUE TITLE
A tiddler for each Tag 

### ISSUE THREAD

**Issue by felixhayashi** [erwanm/tw-aggregator#37]
Hi @erwanm,

I see that you have a tiddler "CommunityTags". Maybe you could make a tiddler for every tag ("Tag - <Tagname>") because then I could create a permalink to this tiddler and stay informed, otherwise a big huge taglist opens with many tags I am not interested in. Also maybe we can as a community decide on special tags (like e.g. #news) that have a special meaning.

Maybe related to #34

**Comment by erwanm** [comment]
Excellent idea! 
I'll do it as soon as I can.

**Comment by felixhayashi** [comment]
:+1:

**Comment by erwanm** [comment]
Finally coded this simple feature.
Not well tested or documented yet, though.
