### ISSUE TITLE
presentation tiddler by transclusion

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#40]

**Comment by twMat** [comment]
Just like you have the [follow url fature](http://erwanm.github.io/tw-community-search/#FollowUrlFeature), the author could include a special "About" tiddler. This tiddler is *actually* included on the tw-aggreagator site! and gives the author an opportunity to present the creation in a desirable way. 

I guess the About shoudl include a local stylesheet (simple; just put it `<style>` here `</style>` in the very tiddler).

This would add a lot more "flavor" to the TW Community Aggreagator site. BTW, this could be an appropriate location for the TW Community Aggregator site to append a "Community Comments" #69  And it woudl make it appear closer to traditional plugin repositories.

**Comment by erwanm** [comment]
Yes, that was the idea: originally it was planned for the wikis, i.e. so that authors would be able to present their own wiki in the aggregator, but of course it applied as well to plugins. 
But even currently there is an implicit way to do it (although briefly): for wikis I use copy the subtitle in the corresponding TWCS wiki tiddler, and for plugins there is a standard "description" field.

**Comment by erwanm** [comment]
now done (for wikis, and not by transclusion but that's not the point)
