### ISSUE TITLE
Remove "warning"

### ISSUE THREAD

**Issue by felixhayashi** [erwanm/tw-aggregator#49]
Hi @erwanm,

I do not think you "warning" text is necessary ("This is an unofficial and experimental wiki. It is, of course, provided without warranty of any kind."). If you for any reason want to keep it, at least make it less bold and better change the heading to something like "please note". It scares the user to see "warning" ;)

-Felix

**Comment by erwanm** [comment]
@felixhayashi 
You're right, of course. I guess it's something I did at the beginning when I was worried that people would blame for every issue. Moved it at the end of the tiddler, where it's much less visible.
