### ISSUE TITLE
switch from rawgit to github.io for the result wiki

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#50]
### Motivations 

- less complicated public address
- wiki stored under the gh-pages branch and not in the master anymore:
  - no more confusion and git being unhappy when the file is modified in the master branch by mistake, and less risk to mess up the public wiki
  - as far as I understand, that should solve the problem of "constant activity" reported on my github page because of the automatic updates on the master branch (not totally sure how that works)
- better separation between the aggregator system and the resulting wiki 
  - also: possibility to have several wikis generated in different ways for different purposes.

### Plan

Most important: avoid users being confused with the change.

1. before announcing, maintain the two versions in order to check that things work
2.  once announced (or maybe a bit later), show it clearly in the old page with the new address + the fact that this version will stop being updated (maybe use $:/tags/AboveStory)
3. leave the non-updated a version for a while (couple of months maybe), then remove it.

Unsure: before or after the next version with plugins list? Or maybe in the same time actually?

**Comment by felixhayashi** [comment]
Hi @erwanm 

just wanted to say, I do the following to avoid url changes in the future:

1. bit.ly/tiddlymap (official public url) which is short and leads the browser automatically to
2. a webspace I own which has a .htaccess with a "Redirect 301" that leads the browser automatically to
3  http://felixhayashi.github.io/TW5-TiddlyMap/index.html

When url changes I only change the redirect in the `.htaccess`.

Maybe a similar solution makes sense for you...

-Felix
