### ISSUE TITLE
make authors/wikis tiddlers nicer with tables

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#64]

**Comment by twMat** [comment]
Not only that;

just like you have the [follow url fature](http://erwanm.github.io/tw-community-search/#FollowUrlFeature), the author could include a special "About" tiddler. This tiddler is *actually* included on the tw-aggreagator site! and gives the author an opportunity to present the creation in a desirable way. 

I guess the About shoudl include a local stylesheet (simple; just put it `<style>` here `</style>` in the very tiddler).

This would add a lot more "flavor" to the TW Community Aggreagator site. BTW, this could be an appropriate location for the TW Community Aggregator site to append a "Community Comments". And it woudl make it appear closer to traditional plugin repositories.

**Comment by erwanm** [comment]
This issue was moved to erwanm/tw-community-search#3
