### ISSUE TITLE
Set Favicon

### ISSUE THREAD

**Issue by twMat** [erwanm/tw-aggregator#66]
@erwanm Great to see you kick on!

Here's... literally... a small contribution;

[Pick the favourite](https://www.google.se/search?q=search+icon+transparent+background&hl=en&biw=1366&bih=653&site=imghp&tbm=isch&source=lnt&tbs=isz:ex,iszw:16,iszh:16), drag it in and just rename it $:/favicon.ico

<:-)

**Comment by erwanm** [comment]
This issue was moved to erwanm/tw-community-search#2
