### ISSUE TITLE
specific name for community tags

### ISSUE THREAD

**Issue by erwanm** [erwanm/tw-aggregator#94]
e.g. prefix "CommunityTag: [title]", in order to avoid name conflicts with wiki or authors tiddlers.

probably a good idea to warn people about the change, in case they have bookmarks.

maybe the implementation should be done in the same time as #93 ?

**Comment by felixhayashi** [comment]
Hi @erwanm, could you explain the meaning of "community tags" please. Is this related to #36?

**Comment by erwanm** [comment]
Hi @felixhayashi, what I call CommunityTags are all the tags collected, and more specifically the individual tiddlers created for each tag to make them "bookmarkable", as you suggested in #37 (but no relation to #36 which is now "CommunityNews")

I realized that there is an issue with tags which have a name which already exists in the wiki: for instance if someone uses the tag "FelixKuppers", in the current version it will be ignored because there is already an author tiddler [with this name](http://erwanm.github.io/tw-community-search/#FelixKuppers). That's why I want to add a specific prefix to the title for all the tags, e.g. "CommunityTag: FelixKuppers", to avoid any name conflict.

Since that would break previous bookmarks that people are using, I'm considering keeping both the current version and the new version at the beginning.

**Comment by felixhayashi** [comment]
Thanks for this clarification @erwanm! These are issues that I never thought about ;) In case you use a tag-prefix I would suggest you choose a shorter one e.g. "cmsr:XY" but please do as you like…

-Felix

**Comment by erwanm** [comment]
forgot to mention the solve in the commit msg, but it was in the big batch of changes from the past few days, together with #93 .
